name: Create release draft

on:
  push:
    tags:
      - 'v*'

jobs:
  create_page:
    runs-on: ubuntu-latest

    steps:
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        draft: true
        prerelease: false

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        es-version: [7.10.1, 7.10.0, 7.9.3, 7.9.2, 7.9.1, 7.9.0, 7.8.1, 7.8.0]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Extract tag version
      id: tag
      run: echo "::set-output name=version::$(echo ${{ github.ref }} | sed -e 's/refs\/tags\/v//')"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build ${{ matrix.es-version }}
      run: ./gradlew -PelasticsearchVersion=${{ matrix.es-version }} clean build
    - name: Upload release asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/distributions/analysis-sudachi-${{ matrix.es-version }}-${{ steps.tag.outputs.version }}.zip
        asset_name: analysis-sudachi-${{ matrix.es-version }}-${{ steps.tag.outputs.version }}.zip
        asset_content_type: application/zip
